### ISSUE TITLE
Error when using @Query

### ISSUE THREAD

**Issue by 0x-r4bbit** [pkozlowski-opensource/ng2-play.ts#2]
Running the exact same code as in https://github.com/pkozlowski-opensource/ng2-play/issues/26 gives me this error:

```
EXCEPTION: Cannot resolve all parameters for Widget(@Query(InnerWidget)). Make sure they all have valid type or annotations.
angular2.min.js:16 STACKTRACE:
angular2.min.js:16 Error
    at t (http://localhost:9000/lib/angular2.min.js:4:22628)
    at new t (http://localhost:9000/lib/angular2.min.js:5:10409)
    at i (http://localhost:9000/lib/angular2.min.js:20:7922)
    at http://localhost:9000/lib/angular2.min.js:20:7570
    at Array.map (native)
    at Function.execute.$traceurRuntime.createClass.map (http://localhost:9000/lib/angular2.min.js:5:345)
    at r (http://localhost:9000/lib/angular2.min.js:20:7545)
    at execute.$traceurRuntime.createClass.resolve (http://localhost:9000/lib/angular2.min.js:20:9559)
    at Function.execute.$traceurRuntime.createClass.createFromBinding (http://localhost:9000/lib/angular2.min.js:21:26105)
    at Function.execute.$traceurRuntime.createClass.createFromType (http://localhost:9000/lib/angular2.min.js:21:27036)
```

**Comment by pkozlowski-opensource** [comment]
Indeed, seeing the same pb here. Not sure what is going on, though. Will wait for .35 and re-test as there were several changes around this area.

**Comment by 0x-r4bbit** [comment]
SGTM 👍

**Comment by 0x-r4bbit** [comment]
Okay you updated the repo. I'll check if this is still an issue.

**Comment by 0x-r4bbit** [comment]
Same error @pkozlowski-opensource any idea?

**Comment by pkozlowski-opensource** [comment]
The only thing that comes to my mind is that we can't use Query on top-level component (the one we are using to bootstrap an app). Did you try it on any of child components?

**Comment by 0x-r4bbit** [comment]
I'm using it in a view component. The bootstrapped component is really just there for bootstrap.

**Comment by pkozlowski-opensource** [comment]
OK, could we start by making it work in a simple plunker first and then I would debug what is the difference with this setup?

**Comment by 0x-r4bbit** [comment]
Sure, do you have a plunkr boilerplate that works with TS?

**Comment by pkozlowski-opensource** [comment]
Nope, no TS plunk I'm afraid :-/

**Comment by 0x-r4bbit** [comment]
Here's an ES6 version: http://plnkr.co/edit/F9rv6yCV6EKyORaG36MS?p=preview

Exactly the same issue

**Comment by pkozlowski-opensource** [comment]
LOL :-) So the question is: did you ever make it work with any setup outside of the ng2 repo?

**Comment by 0x-r4bbit** [comment]
As mentioned and linked here: https://github.com/pkozlowski-opensource/ng2-play/issues/26 Nope

**Comment by 0x-r4bbit** [comment]
I can open an issue on the angular repo if you want

**Comment by pkozlowski-opensource** [comment]
@PascalPrecht I've managed to make it work here: https://github.com/pkozlowski-opensource/ng2-bs/blob/master/src/panel/panel.ts

For the TS version it started to work when I've added `QueryList` type annotation. Not sure of this is a bug (I would say so, IMO it should work without type annotation, especially that in ES6 we don't have type annotations...).

Are you going to open an issue for this or do you want me to do so?

**Comment by 0x-r4bbit** [comment]
That's weird, because I also use `QueryList` and `QueryListAnnotation` in both ng2-play repos and didn't get it to work. But yea, I can open an issue for that.

**Comment by pkozlowski-opensource** [comment]
OK, so this needs to be fixed on the ng2 side: https://github.com/angular/angular/issues/3903
